error_handler:
    matchers:
        fatal: ~
        exception: ~
        user_error: ~
        unknown_file: ~
    log_path: "%kernel.logs_dir%/ErrorHandler"
    logger: elama.error_handler_logger
    renderer: 'auto'

services:
    elama.error_handler:
        class: eLama\ErrorHandler\ErrorHandler
        factory: [eLama\ErrorHandler\ErrorHandlerContainer, getErrorHandler]
        calls:
          - ["stopRenderExceptionErrorPage"]

    elama.error_handler.request_listener:
        class: eLama\ErrorHandler\Bundle\EventListener\ErrorHandlerInitializer
        arguments:
            - "@service_container"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 255 }
            - { name: kernel.event_listener, event: console.command, method: onCommand, priority: 255 }

    core.exceptlistener:
        class: eLama\ErrorHandler\Bundle\EventListener\SymfonyExceptionHandler
        arguments:
            - "%error_handler.renderer%"
        calls:
            - ["stopRenderExceptionErrorPage"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onException, priority: 10 }
            - { name: kernel.event_listener, event: console.exception, method: onException, priority: 255 }


    elama.error_handler_logger:
        class: Monolog\Logger
        factory: [eLama\ErrorHandler\LoggerFactory, createLogger]
        arguments:
            - "%error_handler.log_path%"
        calls:
            - [pushHandler, ["@graylog_handler"]]

    graylog_handler:
        class: Monolog\Handler\GelfHandler
        factory: [eLama\ErrorHandler\Bundle\GraylogHandlerFactory, create]
        arguments:
            - "@service_container"
